### ISSUE TITLE
perf_event_open failed: No such file or directory

### ISSUE THREAD

**Issue by SamuelGong** [rcrane/TEEMon#4]
Hi TEEMon Team,

I was following the instruction in `README.md` and finally ends up with six containers launched. However, all were up but `ebpf_exporter` kept restarting. Here was the result of performing `docker logs` accordingly:

```
perf_event_open failed: No such file or directory
2021/02/22 13:29:24 Error attaching exporter: failed to attach perf event 0:3 to "on_cache_miss" in program "llcstat": failed to attach BPF perf event: invalid argument
```

For enjoying SGX-enabled features, I was conducting my experiment with `DC4s_v2` virtual machine provided by Azure Confidential Computing. For your reference, here is the complete executing result of `docker info` in my VM: 

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 64
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1039-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: accvm
 ID: XE5B:CYTG:I7NV:N3OV:LQ24:QQJ4:TBLZ:DH2Q:TIC4:4XPI:BSOO:SJAM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

Like what is implied in the [README.md](https://github.com/jvm-profiling-tools/async-profiler/blob/master/README.md#troubleshooting) of Project `async-profiler`, the problem related to `perf_event_open()` might result from running in virtual machine instead of a physical one. However, I currently do not have any access to SGX-enabled local machine. It would be great if you can help me circumvent this issue.

BTW, what I have already tried but did not work:

* Setting `/proc/sys/kernel/perf_event_paranoid` to 0 or 1;
* Add `--security-opt seccomp=unconfined` when running the container `ebpf_exporter`.

**Comment by SamuelGong** [comment]
Hi TEEMon Team,

May I have your hand?

**Comment by rcrane** [comment]
Sorry, I have currently no time to dive deeply into the issue but I believe your assumption wrt the VM is correct.

A hacky circumvention that you could try is to remove blocks in https://github.com/rcrane/TEEMon/blob/master/exporters/ebpf_exporter/configfile/sgx.yaml, e.g. line 5-33, according to the error message.

However, I believe you'll end up removing most if not all code blocks in that file which will essentially remove the ebf_exporter.

**Comment by SamuelGong** [comment]
Thanks for your suggestion. I have removed line 2 to 75 in the file

https://github.com/rcrane/TEEMon/blob/349dd1850fd9790cf5110de47ddb2bfc966d1732/exporters/ebpf_exporter/configfile/sgx.yaml#L2

and finally I saw **all the containers up** as follows, including the `ebpf_exporter`. So your advice should work.

```bash
$ docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS         PORTS                                            NAMES
b71cdfd0e445   prom/prometheus:v2.8.1   "/bin/prometheus --c…"   4 minutes ago   Up 3 minutes   0.0.0.0:9090->9090/tcp                           teemon_prometheus_1
0b65292c15db   grafana/grafana:6.5.0    "/run.sh"                4 minutes ago   Up 3 minutes   3000/tcp, 0.0.0.0:9091->9091/tcp                 teemon_grafana_1
3e32373fa210   ebpf_exporter:latest     "ebpf_exporter --con…"   4 minutes ago   Up 3 minutes   0.0.0.0:9440->9440/tcp                           teemon_ebpf-exporter_1
8681a019226d   sgx_exporter:latest      "/bin/sh -c 'python …"   4 minutes ago   Up 3 minutes   0.0.0.0:9441->9441/tcp                           teemon_sgx-exporter_1
2afc764b1dd7   google/cadvisor          "/usr/bin/cadvisor -…"   4 minutes ago   Up 3 minutes   0.0.0.0:8080->8080/tcp, 0.0.0.0:9443->9443/tcp   teemon_cadvisor_1
4827c7912cac   prom/node-exporter       "/bin/node_exporter …"   4 minutes ago   Up 3 minutes   9100/tcp, 0.0.0.0:9442->9442/tcp                 teemon_node-exporter_1
```

On the other hand, **I still cannot see any metrics** in the browser. The dashboard just looked like:

<img width="1126" alt="Screen Shot 2021-03-02 at 12 06 56 PM" src="https://user-images.githubusercontent.com/25379688/109595582-ce609100-7b4f-11eb-8f15-14763f19a663.png">

So there is something they call **Template Init Failed**. Where should I debug? For your reference, the output of running `./start.sh` is pasted below.

```
SGX driver NOT installed!
Sending build context to Docker daemon  744.4kB^M^M
Step 1/15 : FROM golang:1.16.0-buster as builder
 ---> f15d23d96763
Step 2/15 : RUN apt-get -q update && apt-get -q upgrade -y
 ---> Using cache
 ---> c786f76535a7
Step 3/15 : RUN apt-get -q autoremove
 ---> Using cache
 ---> 773f03397861
Step 4/15 : RUN apt-get install -y -q apt-transport-https apt-utils linux-headers-amd64 cmake llvm libelf-dev libclang-dev bison flex python zlib1g-dev luajit build-essential arping libluajit-5.1-dev apt-utils iperf git autotools-dev automake autogen
 ---> Using cache
 ---> bc1fa0c8a409
Step 5/15 : RUN git clone https://github.com/HewlettPackard/netperf.git
 ---> Using cache
 ---> 38735aefcada
Step 6/15 : RUN cd netperf && ./autogen.sh && ./configure && make -j4 &&  make install
 ---> Using cache
 ---> 8c5aa964663e
Step 7/15 : RUN curl -sL https://github.com/iovisor/bcc/releases/download/v0.18.0/bcc-src-with-submodule.tar.gz | tar xvz  -C  /tmp/
 ---> Using cache
 ---> 85177c34df7b
Step 8/15 : RUN cd /tmp/bcc && cmake . && make -j4 && make install
 ---> Using cache
 ---> 371bb3811fd2
Step 9/15 : COPY ./ /go/ebpf_exporter
 ---> Using cache
 ---> ceacd1f4e0f1
Step 10/15 : RUN cd /go/ebpf_exporter && go mod vendor && go mod download && GOPATH="" GOPROXY="off" GOFLAGS="-mod=vendor" go install -v ./...
 ---> Using cache
 ---> f70a4072f982
Step 11/15 : RUN ls -r /root/go/bin/ebpf_exporter
 ---> Using cache
 ---> 3b7530d6d6ff
Step 12/15 : RUN cp /root/go/bin/ebpf_exporter /usr/bin/ebpf_exporter
 ---> Using cache
 ---> 20be6487f9a6
Step 13/15 : COPY ./configfile/sgx.yaml /etc/ebpf_exporter/
 ---> Using cache
 ---> 0912323809c6
Step 14/15 : ENTRYPOINT [ "ebpf_exporter" ]
 ---> Using cache
 ---> 37dc3be2ee0d
Step 15/15 : CMD [ "--config.file=/etc/ebpf_exporter/sgx.yaml" ]
 ---> Using cache
 ---> 7d35ae3b942f
Successfully built 7d35ae3b942f
Successfully tagged ebpf_exporter:latest
Sending build context to Docker daemon  9.216kB^M^M
Step 1/5 : FROM python:3-alpine
 ---> c89f09476494
Step 2/5 : RUN mkdir /SGX-Exporter
 ---> Using cache
 ---> 72dd4e25e880
Step 3/5 : RUN cd /SGX-Exporter &&     pip install flask
 ---> Using cache
 ---> ef13ce83c791
Step 4/5 : COPY sgx_exporter.py /SGX-Exporter
 ---> Using cache
 ---> 8a1beddd4da8
Step 5/5 : CMD python /SGX-Exporter/sgx_exporter.py -p /host/sys/module/isgx/parameters/
 ---> Using cache
 ---> 347b8d15c132
Successfully built 347b8d15c132
Successfully tagged sgx_exporter:latest
re-using old storage dir
You may now open http://localhost:9091
```

**Comment by rcrane** [comment]
Do you get more information when you hover over the small red exclamation marks?

Quick guess:
You might be seeing this because of issue #1 and https://github.com/SamuelGong/TEEMon/commit/c0b14824d4944b7d42b7476b4678f88209278306.

The complete TEEMon should create containers that expose the following web-services:

Grafana: http://0.0.0.0:9091
Prometheus: http://0.0.0.0:9090
EBPF-Exporter: http://0.0.0.0:9440/metrics   
SGX-Exporter: http://0.0.0.0:9441/metrics 
Node-Exporter: http://0.0.0.0:9442/metrics 
Container-Exporter: http://0.0.0.0:9443/metrics

Can you check those and also if you can open http://0.0.0.0:9090/targets or http://127.0.0.1:9090/targets in your VM? 
That page should also list the four exporters that pipe data into Prometheus.

One possibility might be that the containers cannot find each other.
Not using the host mode for networking (https://github.com/SamuelGong/TEEMon/commit/c0b14824d4944b7d42b7476b4678f88209278306) might have lead to this. Not sure.

You might have to adapt datasource.yml, prometheus.yml, and all other files where you find "0.0.0.0" towards the ip addresses of your containers.

**Comment by SamuelGong** [comment]
Hi TEEMon Team,

Thanks for your prompt help!

As the new syntax of docker-compose does not allow simultaneous definition of `network_mode` and `port`, we still new to tackle issue #1. As my previous advocate in #2 seems not to work, I thus tried to fix the problem in the other direction, as shown in the pull request #5. That is, commenting `port`, instead of `network_mode` like I did before. Currently, it looks to work for me.

So I think we can come back to this issue. For your information, here is what I get for the **SGX dashboard**.

<img width="1069" alt="Screen Shot 2021-03-02 at 3 30 56 PM" src="https://user-images.githubusercontent.com/25379688/109613558-4a68d200-7b6c-11eb-9713-d882efbaf5cf.png">

As you can see, the total number of eBPF programs I can have is six, those are:

* syscalls
* sched_switches_to
* sched_switches_from
* perf_sw_events
* page_fault_user
* page_fault_kernel

Obviously I don't have cache statistics, as I have commented related code in `TEEMon/exporters/ebpf_exporter/configfile/sgx.yaml`. This is not very satisfying. I will keep searching walkaround regarding running on VMs.

**Comment by SamuelGong** [comment]
I currrently find that only commenting Line 31-75 of the file https://github.com/rcrane/TEEMon/blob/349dd1850fd9790cf5110de47ddb2bfc966d1732/exporters/ebpf_exporter/configfile/sgx.yaml#L31, instead of 2-75 as I did before, can give me one more eBPF program: `cachestat`.

Still, I am not very satisfied about it.

<img width="1121" alt="Screen Shot 2021-03-04 at 1 34 10 PM" src="https://user-images.githubusercontent.com/25379688/109916295-4fee2580-7cee-11eb-91f9-31008a080001.png">

It seems that `llcstat` should be very helpful to my measurement, however, I have not find my way out to having that statisics.

**Comment by SamuelGong** [comment]
I have revisited this issue. Let me first paste the error message again:

```
perf_event_open failed: No such file or directory
2021/02/22 13:29:24 Error attaching exporter: failed to attach perf event 0:3 to "on_cache_miss" in program "llcstat": failed to attach BPF perf event: invalid argument
```

Today I located the source of the error in the bcc project

https://github.com/iovisor/bcc/blob/999939785e28d756e9a44526c76f00b9dc10154b/src/cc/libbpf.c#L1402

So two lines before we can see that the program was trying to perform system call `__NR_perf_event_open`.  Then I referred to the [Linux manual](https://man7.org/linux/man-pages/man2/perf_event_open.2.html), and I ended up reading words like

```
If type is PERF_TYPE_HARDWARE, we are measuring one of the generalized hardware CPU events.  Not all of these are available on all platforms.
```

So I came to realize that I might first directly check the availability of the related hardware events in this issue:

* PERF_COUNT_HW_CACHE_REFERENCES
* PERF_COUNT_HW_CACHE_MISSES

What I used to confirmed that **my VM did not support both events** was the following command

```bash
$ sudo perf list cache

List of pre-defined events (to be used in -e):
```

So anyone having the same issue may first do the similar check to me. Anyway, it should be unlikely that my issue can be resolved, as it makes sense that VM vendors does not virtualize related counters. Hence, I am here asking some final questions:

*Theoretically, can we reframe the code for supporting such a case, i.e., is it the only way to get or calculate the EPC related metrics through `perf`?* Of course this is only academic discussion and please understand that I do not expect real reframe engineering :)

**Comment by rcrane** [comment]
I'm not aware of a non-perf way to get the kernel cache misses.
Note that some stats regarding SGX are gathered from the filessystem at "/sys/module/isgx/parameters/" (if using the Scontain-driver).
See https://github.com/rcrane/TEEMon/blob/master/exporters/sgx_exporter/sgx_exporter.py for details.

**Comment by SamuelGong** [comment]
> I'm not aware of a non-perf way to get the kernel cache misses.
> Note that some stats regarding SGX are gathered from the filessystem at "/sys/module/isgx/parameters/" (if using the Scontain-driver).
> See https://github.com/rcrane/TEEMon/blob/master/exporters/sgx_exporter/sgx_exporter.py for details.

Thanks a lot for your reminder! I may close this issue now.
